### ISSUE TITLE
Can it work without the mask images?

### ISSUE THREAD

**Issue by liyiyue2021** [ByChelsea/VAND-APRIL-GAN#13]
I want to use this perfect work in a new dataset, but the dataset doesn't have mask labels.  My objective is to perform image-level anomaly detection (normal or abnormal classification). Is that possible to achieve this using this code?

**Comment by ByChelsea** [comment]
Can you please provide more information about the new dataset (if possible)? Is it similar to datasets like MVTec-AD and VisA, or more like ImageNet and CIFAR-10? I might need more information to assess this.

**Comment by liyiyue2021** [comment]
This is a medical dataset (images of brain lesions) that has been used for anomaly detection tasks before, but without the information on masks for the abnormal regions.

**Comment by liyiyue2021** [comment]
The training process is only normal images, testing is normal and abnormal images

**Comment by ByChelsea** [comment]
Since our method is designed for zero-shot applications, you can attempt testing it on your dataset by simply **changing the text prompt**. However, due to the significant disparity between medical tasks and industrial anomaly detection, direct testing may not yield satisfactory results. Therefore, you can also consider retraining our method by generating **synthetic anomalies** (similar to [DRAEM](https://github.com/VitjanZ/DRAEM)) to better align with your specific application.

The above is just my suggestion. Since I'm not specialized in medical tasks, my ideas may not be entirely suitable. Please take them as a reference. :)

**Comment by liyiyue2021** [comment]
Thank you so much for your patient explanation and response. I have one more small request: could you please share the manual download link for the CLIP model ( ViT-L-14-336)?

**Comment by ByChelsea** [comment]
Sure! You can find all the links you need [here](https://github.com/mlfoundations/open_clip/blob/e7b39e4321b2c59e7dc2cdf83cddd7742cd9e6a0/src/open_clip/pretrained.py#L182).

**Comment by liyiyue2021** [comment]
Thanks so much.
