### ISSUE TITLE
What type of GPU are you using and how long does it take

### ISSUE THREAD

**Issue by ZS-YANG** [ByChelsea/VAND-APRIL-GAN#25]
Thanks for your great work! 
By the way, what type of GPU are you using and how long does it take?🙌

**Comment by ByChelsea** [comment]
When training on VisA, fine-tuning takes about 5 minutes per epoch. Since the calculation of the PRO metric is very slow, if testing is conducted after each epoch, it would take about 27 minutes per epoch. My experiments were conducted on an RTX 3090  (its power may have been limited at that time, but I don't remember).

**Comment by ZS-YANG** [comment]
Get it, thx  ! 😝
